use crate::models::{DesktopTextSettings, PresetDefinition, PresetStatus, RenderingSettings};

const DESKTOP_SETTINGS: DesktopTextSettings = DesktopTextSettings {
    font_smoothing: "2",
    font_smoothing_type: 1,
    font_smoothing_gamma: 1850,
    font_smoothing_orientation: 1,
};

const RENDERING_SETTINGS: RenderingSettings = RenderingSettings {
    pixel_structure: 0,
    gamma_level: 1850,
    clear_type_level: 0,
    text_contrast_level: 5,
};

const HARMONY_SUBSTITUTES: &[(&str, &str)] = &[
    ("Segoe UI", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Light", "HarmonyOS Sans SC"),
    ("Segoe UI Semilight", "HarmonyOS Sans SC"),
    ("Segoe UI Semibold", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Black", "HarmonyOS Sans SC"),
    ("Segoe UI Variable", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Variable Text", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Variable Text Light", "HarmonyOS Sans SC"),
    ("Segoe UI Variable Text Semibold", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Variable Display", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Variable Display Light", "HarmonyOS Sans SC"),
    ("Segoe UI Variable Display Semibold", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Variable Small", "HarmonyOS Sans SC Medium"),
    ("Segoe UI Variable Small Light", "HarmonyOS Sans SC"),
    ("Segoe UI Variable Small Semibold", "HarmonyOS Sans SC Medium"),
    ("Microsoft YaHei", "HarmonyOS Sans SC Medium"),
    ("Microsoft YaHei UI", "HarmonyOS Sans SC Medium"),
    ("Microsoft YaHei Light", "HarmonyOS Sans SC"),
    ("Microsoft YaHei UI Light", "HarmonyOS Sans SC"),
    ("Microsoft YaHei Semibold", "HarmonyOS Sans SC Medium"),
    ("Microsoft YaHei UI Semibold", "HarmonyOS Sans SC Medium"),
];

const SARASA_SUBSTITUTES: &[(&str, &str)] = &[
    ("Segoe UI", "Sarasa UI SC SemiBold"),
    ("Segoe UI Light", "Sarasa UI SC"),
    ("Segoe UI Semilight", "Sarasa UI SC"),
    ("Segoe UI Semibold", "Sarasa UI SC SemiBold"),
    ("Segoe UI Black", "Sarasa UI SC"),
    ("Segoe UI Variable", "Sarasa UI SC SemiBold"),
    ("Segoe UI Variable Text", "Sarasa UI SC SemiBold"),
    ("Segoe UI Variable Text Light", "Sarasa UI SC"),
    ("Segoe UI Variable Text Semibold", "Sarasa UI SC SemiBold"),
    ("Segoe UI Variable Display", "Sarasa UI SC SemiBold"),
    ("Segoe UI Variable Display Light", "Sarasa UI SC"),
    ("Segoe UI Variable Display Semibold", "Sarasa UI SC SemiBold"),
    ("Segoe UI Variable Small", "Sarasa UI SC SemiBold"),
    ("Segoe UI Variable Small Light", "Sarasa UI SC"),
    ("Segoe UI Variable Small Semibold", "Sarasa UI SC SemiBold"),
    ("Microsoft YaHei", "Sarasa UI SC SemiBold"),
    ("Microsoft YaHei UI", "Sarasa UI SC SemiBold"),
    ("Microsoft YaHei Light", "Sarasa UI SC"),
    ("Microsoft YaHei UI Light", "Sarasa UI SC"),
    ("Microsoft YaHei Semibold", "Sarasa UI SC SemiBold"),
    ("Microsoft YaHei UI Semibold", "Sarasa UI SC SemiBold"),
];

const SOURCE_HAN_SUBSTITUTES: &[(&str, &str)] = &[
    ("Segoe UI", "Source Han Sans CN Medium"),
    ("Segoe UI Light", "Source Han Sans CN"),
    ("Segoe UI Semilight", "Source Han Sans CN"),
    ("Segoe UI Semibold", "Source Han Sans CN Medium"),
    ("Segoe UI Black", "Source Han Sans CN"),
    ("Segoe UI Variable", "Source Han Sans CN Medium"),
    ("Segoe UI Variable Text", "Source Han Sans CN Medium"),
    ("Segoe UI Variable Text Light", "Source Han Sans CN"),
    ("Segoe UI Variable Text Semibold", "Source Han Sans CN Medium"),
    ("Segoe UI Variable Display", "Source Han Sans CN Medium"),
    ("Segoe UI Variable Display Light", "Source Han Sans CN"),
    ("Segoe UI Variable Display Semibold", "Source Han Sans CN Medium"),
    ("Segoe UI Variable Small", "Source Han Sans CN Medium"),
    ("Segoe UI Variable Small Light", "Source Han Sans CN"),
    ("Segoe UI Variable Small Semibold", "Source Han Sans CN Medium"),
    ("Microsoft YaHei", "Source Han Sans CN Medium"),
    ("Microsoft YaHei UI", "Source Han Sans CN Medium"),
    ("Microsoft YaHei Light", "Source Han Sans CN"),
    ("Microsoft YaHei UI Light", "Source Han Sans CN"),
    ("Microsoft YaHei Semibold", "Source Han Sans CN Medium"),
    ("Microsoft YaHei UI Semibold", "Source Han Sans CN Medium"),
];

pub fn preset_definitions() -> Vec<PresetDefinition> {
    vec![
        PresetDefinition {
            id: "harmonyos-sc",
            status: PresetStatus::Ready,
            font_family: "HarmonyOS Sans SC",
            required_fonts: &["HarmonyOS Sans SC", "HarmonyOS Sans SC Medium"],
            font_substitutes: HARMONY_SUBSTITUTES,
            desktop: DESKTOP_SETTINGS,
            rendering: RENDERING_SETTINGS,
        },
        PresetDefinition {
            id: "sarasa-ui-sc",
            status: PresetStatus::Ready,
            font_family: "Sarasa UI SC",
            required_fonts: &["Sarasa UI SC", "Sarasa UI SC SemiBold"],
            font_substitutes: SARASA_SUBSTITUTES,
            desktop: DESKTOP_SETTINGS,
            rendering: RENDERING_SETTINGS,
        },
        PresetDefinition {
            id: "source-han-sans-cn",
            status: PresetStatus::Ready,
            font_family: "Source Han Sans CN",
            required_fonts: &["Source Han Sans CN", "Source Han Sans CN Medium"],
            font_substitutes: SOURCE_HAN_SUBSTITUTES,
            desktop: DESKTOP_SETTINGS,
            rendering: RENDERING_SETTINGS,
        },
        PresetDefinition {
            id: "lxgw-wenkai",
            status: PresetStatus::Soon,
            font_family: "LXGW WenKai",
            required_fonts: &["LXGW WenKai"],
            font_substitutes: &[],
            desktop: DESKTOP_SETTINGS,
            rendering: RENDERING_SETTINGS,
        },
        PresetDefinition {
            id: "opposans",
            status: PresetStatus::Soon,
            font_family: "OPPOSans",
            required_fonts: &["OPPOSans 3.0"],
            font_substitutes: &[],
            desktop: DESKTOP_SETTINGS,
            rendering: RENDERING_SETTINGS,
        },
        PresetDefinition {
            id: "inter-harmonyos",
            status: PresetStatus::Soon,
            font_family: "Inter + HarmonyOS",
            required_fonts: &["Inter", "HarmonyOS Sans SC"],
            font_substitutes: &[],
            desktop: DESKTOP_SETTINGS,
            rendering: RENDERING_SETTINGS,
        },
    ]
}
