import type { PresetMeta } from "../types";

export const presetCatalog: PresetMeta[] = [
  {
    id: "harmonyos-sc",
    name: "HarmonyOS Sans SC",
    tag: "现代干净",
    vibe: "轻、稳、通透",
    description: "最稳的一套升级方案，不抢戏，但会把整个 Windows 一下子拉干净。",
    recommendedFor: "适合想要长期默认、几乎不翻车的人。",
    heroLine: "整个桌面一下子干净了",
    englishLine: "Make Windows typography feel calm, clean and intentional.",
    noteLine: "稳妥、现代、耐看，适合作为长期默认。",
    previewFont: "\"HarmonyOS Sans UI\", \"HarmonyOS Sans SC\", sans-serif",
    accentClass: "from-[#dce8ff] via-[#eaf2ff] to-[#f7fbff]",
  },
  {
    id: "sarasa-ui-sc",
    name: "更纱黑体",
    tag: "沉稳扎实",
    vibe: "硬朗、清晰、耐读",
    description: "笔画存在感更强，正文更抓眼，看代码、文档和资源管理器时更有支撑感。",
    recommendedFor: "适合觉得 Windows 默认太细、太飘的人。",
    heroLine: "正文更扎实，一眼更稳",
    englishLine: "Sharper strokes, stronger presence, less visual fatigue.",
    noteLine: "开发、文档、长时间阅读都会更稳。",
    previewFont: "\"Sarasa UI SC\", \"HarmonyOS Sans UI\", sans-serif",
    accentClass: "from-[#ddf6ee] via-[#edfdf8] to-[#f8fffd]",
  },
  {
    id: "source-han-sans-cn",
    name: "思源黑体 CN",
    tag: "中性克制",
    vibe: "标准、平衡、专业",
    description: "跨平台一致性最强的一套，不抢戏，但每个细节都稳稳落在正确的位置。",
    recommendedFor: "适合想要中性、严谨、长期耐看的系统风格。",
    heroLine: "文字回到秩序里",
    englishLine: "Balanced proportions for a quieter, more professional desktop.",
    noteLine: "标准、克制、通用，适合长期主力使用。",
    previewFont: "\"Source Han Sans CN\", \"HarmonyOS Sans UI\", sans-serif",
    accentClass: "from-[#e4ebfb] via-[#f1f5fd] to-[#fafcff]",
  },
  {
    id: "lxgw-wenkai",
    name: "霞鹜文楷",
    tag: "人文温润",
    vibe: "书卷气、柔和、特别",
    description: "给 Windows 留一点情绪。它更像一本纸书，而不是工业面板，适合偏写作和阅读。",
    recommendedFor: "适合想把电脑变得更有呼吸感的人。",
    heroLine: "给系统一点呼吸感",
    englishLine: "A softer, more literary texture for the everyday desktop.",
    noteLine: "文档、写作、阅读场景会更有气质。",
    previewFont: "\"LXGW WenKai\", \"HarmonyOS Sans UI\", serif",
    accentClass: "from-[#ffe7d4] via-[#fff4ec] to-[#fffaf7]",
  },
  {
    id: "opposans",
    name: "OPPOSans",
    tag: "科技几何",
    vibe: "利落、克制、锐",
    description: "更偏工业设计感，边缘更利落，适合高分屏和极简桌面，整体会显得更冷一点。",
    recommendedFor: "适合高 DPI 屏和偏硬朗的视觉偏好。",
    heroLine: "界面像重新磨过一遍",
    englishLine: "Crisp geometry for a sharper and more technical interface.",
    noteLine: "先导入字体文件，再一键应用。",
    previewFont: "\"OPPOSans\", \"HarmonyOS Sans UI\", sans-serif",
    accentClass: "from-[#dde1ff] via-[#eef1ff] to-[#fafbff]",
  },
  {
    id: "inter-harmonyos",
    name: "Inter + HarmonyOS",
    tag: "UI 极致",
    vibe: "英数极净、中日韩稳",
    description: "英文和数字更像设计工具里的 Inter，中文回退到 HarmonyOS，整体节奏更像精修过的 UI。",
    recommendedFor: "适合特别在意英文、数字和界面细节的人。",
    heroLine: "中英文终于同频了",
    englishLine: "Inter for Latin, HarmonyOS for CJK, with a calmer macOS-like rhythm.",
    noteLine: "更接近设计工具和 macOS 那种克制感。",
    previewFont: "\"Inter\", \"HarmonyOS Sans UI\", sans-serif",
    accentClass: "from-[#dcebff] via-[#edf6ff] to-[#fafcff]",
  },
];
