import type { PresetMeta, RenderStyleId } from "../types";

export const presetCatalog: PresetMeta[] = [
  {
    id: "harmonyos-sc",
    sceneName: "默认推荐",
    fontFamily: "HarmonyOS Sans SC",
    shortTag: "现代干净",
    mood: "通用、稳定、长期默认",
    description: "最稳的一套升级方案。它不会过分强调个性，但会把整个 Windows 的气质一下子拉干净。",
    recommendedFor: "适合想要长期默认、几乎不翻车、日常办公和浏览都舒服的人。",
    headline: "把系统调成更顺眼",
    englishLine: "A calmer, cleaner baseline for the everyday Windows desktop.",
    previewFont: '"HarmonyOS Sans UI", "HarmonyOS Sans SC", sans-serif',
    accentClass: "from-[#dce8ff] via-[#eef4ff] to-[#fbfdff]",
    compatibility: "稳定",
    tags: ["通用", "稳定", "长期默认"],
    screens: ["2K", "4K", "150% 缩放"],
  },
  {
    id: "source-han-sans-cn",
    sceneName: "清爽办公",
    fontFamily: "思源黑体 CN",
    shortTag: "中性克制",
    mood: "标准、平衡、专业",
    description: "跨平台一致性很强的一套，不抢戏，但每个细节都稳稳落在正确的位置。",
    recommendedFor: "适合想要中性、严谨、长期耐看的系统风格。",
    headline: "文字回到秩序里",
    englishLine: "Balanced proportions for a quieter, more professional desktop.",
    previewFont: '"Source Han Sans CN", "HarmonyOS Sans UI", sans-serif',
    accentClass: "from-[#e5ebfb] via-[#f2f5fd] to-[#fbfcff]",
    compatibility: "稳定",
    tags: ["办公", "克制", "跨平台"],
    screens: ["2K", "4K", "多软件混用"],
  },
  {
    id: "sarasa-ui-sc",
    sceneName: "代码清晰",
    fontFamily: "更纱黑体",
    shortTag: "沉稳扎实",
    mood: "硬朗、清晰、耐读",
    description: "笔画更有抓地力，信息密度高一点时也能稳住，特别适合代码和文件列表。",
    recommendedFor: "适合开发者、重度办公，以及长时间看小字号文字的人。",
    headline: "让界面更利落",
    englishLine: "Sharper strokes and steadier small text for code-heavy work.",
    previewFont: '"Sarasa UI SC", "HarmonyOS Sans UI", sans-serif',
    accentClass: "from-[#dcf5ee] via-[#eefcf7] to-[#fbfffd]",
    compatibility: "谨慎",
    tags: ["代码", "小字号", "信息密度"],
    screens: ["1080p", "2K", "100% 到 125%"],
  },
  {
    id: "lxgw-wenkai",
    sceneName: "阅读温润",
    fontFamily: "霞鹜文楷",
    shortTag: "人文温润",
    mood: "书卷气、柔和、特别",
    description: "给 Windows 留一点情绪。它更像一本纸书，不是工业面板，阅读和写作会更有呼吸感。",
    recommendedFor: "适合文档、写作、阅读场景，不建议所有人都拿它做长期系统默认。",
    headline: "给系统一点呼吸感",
    englishLine: "A softer, more literary texture for the everyday desktop.",
    previewFont: '"LXGW WenKai", "HarmonyOS Sans UI", serif',
    accentClass: "from-[#ffe7d6] via-[#fff3eb] to-[#fff9f6]",
    compatibility: "谨慎",
    tags: ["阅读", "写作", "风格强"],
    screens: ["2K", "4K", "中大字号正文"],
  },
  {
    id: "inter-harmonyos",
    sceneName: "设计混排",
    fontFamily: "Inter + HarmonyOS",
    shortTag: "UI 极致",
    mood: "英文极净、中日韩稳",
    description: "英文字母和数字交给 Inter，中文回到 HarmonyOS。更接近设计工具和高分屏产品界面的混排节奏。",
    recommendedFor: "适合特别在意英文、数字、界面细节，以及高分屏观感的人。",
    headline: "中英终于同频了",
    englishLine: "Inter for Latin, HarmonyOS for CJK, with a cleaner product feel.",
    previewFont: '"Inter", "HarmonyOS Sans UI", sans-serif',
    accentClass: "from-[#dcebff] via-[#edf6ff] to-[#fafcff]",
    compatibility: "稳定",
    tags: ["设计感", "高分屏", "英文数字"],
    screens: ["2K", "4K", "设计和产品工作流"],
  },
  {
    id: "opposans",
    sceneName: "自定义导入推荐",
    fontFamily: "OPPOSans",
    shortTag: "科技几何",
    mood: "需导入、硬朗、锐",
    description: "更偏工业设计感，边缘利落，适合高分屏和极简桌面。建议先导入字体，再决定要不要长期使用。",
    recommendedFor: "适合喜欢更冷一点、更硬朗一点视觉风格的人。",
    headline: "把界面磨得更利",
    englishLine: "Crisp geometry for a sharper and more technical interface.",
    previewFont: '"OPPOSans", "HarmonyOS Sans UI", sans-serif',
    accentClass: "from-[#dde2ff] via-[#eef1ff] to-[#fafbff]",
    compatibility: "实验",
    tags: ["自定义", "高分屏", "偏硬朗"],
    screens: ["2K", "4K", "极简桌面"],
  },
];

export const renderStyleCatalog: Array<{
  id: RenderStyleId;
  label: string;
  summary: string;
}> = [
  { id: "clear", label: "清晰", summary: "边缘更利，小字号优先。" },
  { id: "balanced", label: "平衡", summary: "默认推荐，清晰和舒适兼顾。" },
  { id: "soft", label: "柔和", summary: "灰度更松，长时间看更温和。" },
  { id: "reading", label: "阅读", summary: "长文本更耐看，刺感更低。" },
  { id: "code", label: "代码", summary: "字符辨识更强，列表更稳。" },
  { id: "rounded", label: "圆润观感", summary: "高分屏更圆顺，观感更现代。" },
];
